# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Onur Ferhat
tagline:          'Personal page'
description:      'Personal webpage containing information about past/current projects and activities.'
url:              http://onurferhat.com
baseurl:          /

author:
  name:           'Onur Ferhat'
  url:            https://onurferhat.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tiendan
